/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade10.view;

import br.com.ifba.atividade10.java.LogAuditoria;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Bruno
 */
public class TelaLogAuditoria extends javax.swing.JFrame {
    private DefaultTableModel modeloTabela;
    /**
     * Creates new form TelaLogAuditoria
     */
    public TelaLogAuditoria() {
        initComponents();
        configurarTabela();
        carregarTodosLogs(); // carrega ao abrir
        // Adicionar listeners dos botões:
        btnFechar.addActionListener(e -> dispose());
        btnPesquisar.addActionListener(e -> realizarBusca());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void configurarTabela() {
        modeloTabela = new DefaultTableModel(
            new Object[]{"ID", "Ação", "Data - Hora"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // tabela não editável
            }
        };
        tblAuditoria.setModel(modeloTabela);
    }

    private void carregarTodosLogs() {
        // TODO: buscar lista real do LogAuditoria (do banco ou memória)
        List<LogAuditoria> logs = LogAuditoria.buscarTodos(); // Exemplo
        preencherTabela(logs);
    }

    private void realizarBusca() {
        String filtro = txtFiltro.getText().trim();
        // TODO: implementar filtro real, aqui exemplo vazio:
        List<LogAuditoria> logsFiltrados = LogAuditoria.buscarPorFiltro(filtro);
        preencherTabela(logsFiltrados);
    }

    private void preencherTabela(List<LogAuditoria> logs) {
        modeloTabela.setRowCount(0); // limpa tabela
        for (LogAuditoria log : logs) {
            modeloTabela.addRow(new Object[]{
                log.getId(),
                log.getMensagem(),        
                log.getDataHora().toString() 
            });
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogDeAuditoria = new javax.swing.JLabel();
        lblFiltro = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAuditoria = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogDeAuditoria.setText("Log de Auditoria");
        getContentPane().add(lblLogDeAuditoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        lblFiltro.setText("Filtro:");
        getContentPane().add(lblFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        getContentPane().add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 160, -1));

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        tblAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Data - Hora"
            }
        ));
        jScrollPane1.setViewportView(tblAuditoria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 290));

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        realizarBusca();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();  // Fecha a janela atual
    TelaPrincipal telaPrincipal = new TelaPrincipal();
    telaPrincipal.setVisible(true);
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogAuditoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblLogDeAuditoria;
    private javax.swing.JTable tblAuditoria;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
