/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

/**
 *
 * @author Bruno
 */
public class Contador extends javax.swing.JFrame {

    /**
     * Creates new form Contador
     */
    public Contador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInicio = new javax.swing.JLabel();
        lblFim = new javax.swing.JLabel();
        lblPasso = new javax.swing.JLabel();
        sldInicio = new javax.swing.JSlider();
        sldFim = new javax.swing.JSlider();
        sldPasso = new javax.swing.JSlider();
        btnContar = new javax.swing.JButton();
        lblInicioValor = new javax.swing.JLabel();
        lblFimValor = new javax.swing.JLabel();
        lblPassoValor = new javax.swing.JLabel();
        txtContador = new javax.swing.JScrollPane();
        txtContagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicio.setText("Início");
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblFim.setText("Fim");
        getContentPane().add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblPasso.setText("Passo");
        getContentPane().add(lblPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        sldInicio.setMaximum(10);
        sldInicio.setValue(0);
        sldInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lblInicioValor(evt);
            }
        });
        getContentPane().add(sldInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        sldFim.setMaximum(20);
        sldFim.setMinimum(1);
        sldFim.setValue(0);
        sldFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lblFimValor(evt);
            }
        });
        getContentPane().add(sldFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        sldPasso.setMaximum(5);
        sldPasso.setMinimum(1);
        sldPasso.setValue(0);
        sldPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lblPassoValor(evt);
            }
        });
        getContentPane().add(sldPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        btnContar.setText("Contar");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionListener(evt);
            }
        });
        getContentPane().add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        lblInicioValor.setText("0");
        getContentPane().add(lblInicioValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        lblFimValor.setText("0");
        getContentPane().add(lblFimValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        lblPassoValor.setText("1");
        getContentPane().add(lblPassoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        txtContagem.setColumns(20);
        txtContagem.setRows(5);
        txtContador.setViewportView(txtContagem);

        getContentPane().add(txtContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 240, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblInicioValor(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lblInicioValor
        // TODO add your handling code here:
        lblInicioValor.setText(String.valueOf(sldInicio.getValue()));
    }//GEN-LAST:event_lblInicioValor

    private void lblFimValor(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lblFimValor
        // TODO add your handling code here:
        lblFimValor.setText(String.valueOf(sldFim.getValue()));

    }//GEN-LAST:event_lblFimValor

    private void lblPassoValor(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lblPassoValor
        // TODO add your handling code here:
        lblPassoValor.setText(String.valueOf(sldPasso.getValue()));

    }//GEN-LAST:event_lblPassoValor

    private void ActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionListener
// Obtendo os valores dos sliders
    int inicio = sldInicio.getValue();
    int fim = sldFim.getValue();
    int passo = sldPasso.getValue();

    // Validando se o valor final não é menor que o inicial
    if (fim < inicio) {
        txtContagem.setText("Erro: O valor final não pode ser menor que o inicial.");
        return;
    }

    // Construindo a contagem
    StringBuilder contagem = new StringBuilder();
    for (int i = inicio; i <= fim; i += passo) {
        contagem.append(i).append("\n");
    }

    // Exibindo a contagem no campo de texto
    txtContagem.setText(contagem.toString());        // TODO add your handling code here:
    }//GEN-LAST:event_ActionListener

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblFimValor;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblInicioValor;
    private javax.swing.JLabel lblPasso;
    private javax.swing.JLabel lblPassoValor;
    private javax.swing.JSlider sldFim;
    private javax.swing.JSlider sldInicio;
    private javax.swing.JSlider sldPasso;
    private javax.swing.JScrollPane txtContador;
    private javax.swing.JTextArea txtContagem;
    // End of variables declaration//GEN-END:variables
}
